export const data = {
  customerReviews: [
    {
      id: 'aaa',
      name: 'Alice',
      review: 'Test 1',
      date: '1 October 1995',
    },
    {
      id: 'bbb',
      name: 'Bob',
      review: 'Test 2',
      date: '2 October 1995',
    },
    {
      id: 'ccc',
      name: 'Charlie',
      review: 'Test 3',
      date: '3 October 1995',
    },
  ],
  dummyRestaurants: [
    {
      id: '1',
      name: 'Warung Seblak',
      city: 'Wakanda',
      rating: 5,
      description: '',
      address: '',
      smallPicture: '',
      mediumPicture: '',
      largePicture: '',
      menus: { foods: [], drinks: [] },
      categories: [],
      customerReviews: [],
    },
    {
      id: '2',
      name: 'Warung Kopi',
      city: 'Bali',
      rating: 4,
      description: '',
      address: '',
      smallPicture: '',
      mediumPicture: '',
      largePicture: '',
      menus: { foods: [], drinks: [] },
      categories: [],
      customerReviews: [],
    },
    {
      id: '3',
      name: 'Corner Caffe',
      city: 'Megalodon',
      rating: 3,
      description: '',
      address: '',
      smallPicture: '',
      mediumPicture: '',
      largePicture: '',
      menus: { foods: [], drinks: [] },
      categories: [],
      customerReviews: [],
    },
    {
      id: '4',
      name: 'Restoran Padang',
      city: 'Sunda Empire',
      rating: 4.5,
      description: '',
      address: '',
      smallPicture: '',
      mediumPicture: '',
      largePicture: '',
      menus: { foods: [], drinks: [] },
      categories: [],
      customerReviews: [],
    },
    {
      id: '5',
      name: 'Kafe Kita',
      city: 'Korea Utara',
      rating: 5,
      description: '',
      address: '',
      smallPicture: '',
      mediumPicture: '',
      largePicture: '',
      menus: { foods: [], drinks: [] },
      categories: [],
      customerReviews: [],
    },
  ],
};
